namespace InnNou.Shared.Localization;

// Same lightweight static-dictionary-lookup shape as BulkExcelLocalization, for the order
// confirmation PDF/email's labeled header rows, table columns, and surrounding copy — a
// separate class since it's a distinct concern (order documents, not Excel headers), not a
// generalization of it.
public static class OrderConfirmationLocalization
{
    private static readonly HashSet<string> SupportedLanguages = ["en", "es", "ca"];

    private static readonly Dictionary<string, Dictionary<string, string>> Labels = new()
    {
        ["OrderConfirmationTitle"] = new() { ["en"] = "Order Confirmation", ["es"] = "Confirmación de pedido", ["ca"] = "Confirmació de comanda" },
        ["PurchaseOrderTitle"] = new() { ["en"] = "Purchase Order", ["es"] = "Pedido de compra", ["ca"] = "Comanda de compra" },
        ["OrderConfirmedHeading"] = new() { ["en"] = "Order confirmed", ["es"] = "Pedido confirmado", ["ca"] = "Comanda confirmada" },
        ["NewPurchaseOrderHeading"] = new() { ["en"] = "New purchase order", ["es"] = "Nuevo pedido de compra", ["ca"] = "Nova comanda de compra" },

        ["OrderNumberLabel"] = new() { ["en"] = "Order #", ["es"] = "Pedido n.°", ["ca"] = "Comanda núm." },
        ["DateLabel"] = new() { ["en"] = "Date", ["es"] = "Fecha", ["ca"] = "Data" },
        ["OrganizationLabel"] = new() { ["en"] = "Organization", ["es"] = "Organización", ["ca"] = "Organització" },
        ["WarehouseLabel"] = new() { ["en"] = "Warehouse", ["es"] = "Almacén", ["ca"] = "Magatzem" },
        ["AddressLabel"] = new() { ["en"] = "Address", ["es"] = "Dirección", ["ca"] = "Adreça" },
        ["ContactLabel"] = new() { ["en"] = "Contact", ["es"] = "Contacto", ["ca"] = "Contacte" },
        ["PhoneLabel"] = new() { ["en"] = "Phone", ["es"] = "Teléfono", ["ca"] = "Telèfon" },
        ["EmailLabel"] = new() { ["en"] = "Email", ["es"] = "Correo electrónico", ["ca"] = "Correu electrònic" },

        ["ArticleColumn"] = new() { ["en"] = "Article", ["es"] = "Artículo", ["ca"] = "Article" },
        ["QtyColumn"] = new() { ["en"] = "Qty", ["es"] = "Cant.", ["ca"] = "Quant." },
        ["UnitColumn"] = new() { ["en"] = "Unit", ["es"] = "Unidad", ["ca"] = "Unitat" },
        ["UnitPriceColumn"] = new() { ["en"] = "Unit Price", ["es"] = "Precio unitario", ["ca"] = "Preu unitari" },
        ["LineTotalColumn"] = new() { ["en"] = "Line Total", ["es"] = "Total línea", ["ca"] = "Total línia" },

        ["SubtotalLabel"] = new() { ["en"] = "Subtotal", ["es"] = "Subtotal", ["ca"] = "Subtotal" },
        ["GrandTotalLabel"] = new() { ["en"] = "Grand Total", ["es"] = "Total general", ["ca"] = "Total general" },
        ["GeneratedByLabel"] = new() { ["en"] = "Generated by InnNou —", ["es"] = "Generado por InnNou —", ["ca"] = "Generat per InnNou —" },
        ["EmailFooterNote"] = new()
        {
            ["en"] = "This is an automated confirmation from InnNou. The full order confirmation is attached as a PDF.",
            ["es"] = "Esta es una confirmación automática de InnNou. La confirmación completa del pedido se adjunta en PDF.",
            ["ca"] = "Aquesta és una confirmació automàtica d'InnNou. La confirmació completa de la comanda s'adjunta en PDF."
        },
    };

    public static string NormalizeLanguage(string? languageCode)
    {
        var lang = languageCode?.Trim().ToLowerInvariant();
        return lang is not null && SupportedLanguages.Contains(lang) ? lang : "en";
    }

    public static string Label(string key, string? languageCode)
    {
        var lang = NormalizeLanguage(languageCode);
        if (!Labels.TryGetValue(key, out var byLang))
            return key;

        return byLang.TryGetValue(lang, out var value) ? value : byLang["en"];
    }
}
